<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\core.props"/>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Candoumbe.DataAccess"/>
    <PackageReference Include="Candoumbe.Types.Numerics"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Documents.Ids\Documents.Ids.csproj" />
  </ItemGroup>

</Project>