<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Candoumbe.DataAccess.EFStore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Documents.Objects\Documents.Objects.csproj" />
  </ItemGroup>

</Project>