<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../core.props"/>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StronglyTypedId"/>
    <PackageReference Include="StronglyTypedId.Templates"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="guid-v7.typedid" />
    <None Remove="guid-v7.typedid" />
    <AdditionalFiles Include="guid-v7.typedid" />
  </ItemGroup>

</Project>