<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="candoumbe.pipelines" Version="1.3.0" />
    <PackageVersion Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.21.0" />
    <PackageVersion Include="NodaTime.Serialization.JsonNet" Version="3.0.0" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime" Version="6.0.7" />
  </ItemGroup>
</Project>
