<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\tests.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Documents.API\Documents.API.csproj" />
  </ItemGroup>

</Project>