<Project Sdk="Aspire.AppHost.Sdk/13.1.2">

  <Import Project="../../core.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>00356808-6657-4a2d-99c7-be9ce6d67892</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost"/>
    <PackageReference Include="Aspire.Hosting.PostgreSQL"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Documents.API\Documents.API.csproj" />
    <ProjectReference Include="..\Documents.Migrator\Documents.Migrator.csproj" />
  </ItemGroup>
</Project>