<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\tests.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\Documents.DataStores\Documents.DataStores.csproj" />
    <ProjectReference Include="..\..\src\Documents.Mapping\Documents.Mapping.csproj" />
    <ProjectReference Include="..\..\src\Documents.Objects\Documents.Objects.csproj" />
  </ItemGroup>
</Project>